tap "buo/cask-upgrade"
brew "libpng"
brew "xz"
brew "zstd"
brew "jpeg-xl"
brew "ca-certificates"
brew "black"
brew "icu4c@77"
brew "boost"
brew "glib"
brew "capstone"
brew "certifi"
brew "cmake"
brew "node"
brew "commitlint"
brew "coreutils"
brew "doxygen"
brew "python@3.12"
brew "ffmpeg"
brew "gcc"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-crypt"
brew "git-lfs"
brew "gnupg"
brew "gpac"
brew "pkgconf"
brew "hdf5"
brew "iperf3"
brew "jq"
brew "libunwind-headers"
brew "libyaml"
brew "lit"
brew "mas"
brew "mkvtoolnix"
brew "ninja"
brew "openjdk"
brew "pandoc"
brew "pdm"
brew "pinentry-mac"
brew "pre-commit"
brew "pyinstaller"
brew "pylint"
brew "python-setuptools"
brew "python-tk@3.12"
brew "ruby"
brew "scons"
brew "telnet"
brew "tmux"
brew "torsocks"
brew "trash"
brew "virtualenv"
brew "wget"
brew "wireshark"
cask "balenaetcher"
cask "docker"
cask "handbrake"
cask "microsoft-auto-update"
cask "microsoft-teams"
cask "raspberry-pi-imager"
cask "transmission"
cask "virtualbuddy"
cask "vlc"
cask "zoom"
mas "AdBlock", id: 1402042596
mas "Amphetamine", id: 937984704
mas "DaisyDisk", id: 411643860
mas "Developer", id: 640199958
mas "Discovery", id: 1381004916
mas "Gapplin", id: 768053424
mas "Keynote", id: 409183694
mas "Mapper", id: 1589391989
mas "Messenger", id: 1480068668
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft To Do", id: 1274495053
mas "Microsoft Word", id: 462054704
mas "Mini Metro+", id: 1550663539
mas "Mini Motorways", id: 1456188526
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Prime Video", id: 545519333
mas "Snake.io+", id: 6443553808
mas "Speedtest", id: 1153157709
mas "Whisper Transcription", id: 1668083311
vscode "bierner.github-markdown-preview"
vscode "christian-kohler.npm-intellisense"
vscode "codezombiech.gitignore"
vscode "davidanson.vscode-markdownlint"
vscode "dedsec727.jekyll-run"
vscode "docker.docker"
vscode "dotjoshjohnson.xml"
vscode "github.codespaces"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.copilot-workspace"
vscode "github.remotehub"
vscode "github.vscode-pull-request-github"
vscode "hashicorp.hcl"
vscode "hediet.vscode-drawio"
vscode "james-yu.latex-workshop"
vscode "marp-team.marp-vscode"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.powershell"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.remote-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "openai.chatgpt"
vscode "redhat.vscode-yaml"
vscode "streetsidesoftware.code-spell-checker"
vscode "tamasfe.even-better-toml"
vscode "tomoki1207.pdf"
vscode "tsinghua-hexin-joint-institute.gem5-slicc"
vscode "waderyan.gitblame"
vscode "yzane.markdown-pdf"
