#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# Modified to be portable by Bobby R. Bruce.

INSTALL_PYTHON=$HOMEBREW_PREFIX/opt/pre-commit/libexec/bin/python
PRE_COMMIT_CONFIG=.pre-commit-config.yaml
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=commit-msg)


HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")


if [ -f "$PRE_COMMIT_CONFIG" ]; then
    if [ -x "$INSTALL_PYTHON" ]; then
        exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
    elif command -v pre-commit > /dev/null; then
        exec pre-commit "${ARGS[@]}"
    else
        echo '`pre-commit` not found.' 1>&2
        exit 1
    fi
fi
