#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# Modified to be portable by Bobby R. Bruce.

INSTALL_PYTHON="$(which python)"
PRE_COMMIT_CONFIG=.pre-commit-config.yaml
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=commit-msg)

if [ -f "$PRE_COMMIT_CONFIG" ]; then
    if [ -x "$INSTALL_PYTHON" ]; then
        exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
    elif command -v pre-commit > /dev/null; then
        exec pre-commit "${ARGS[@]}"
    else
        echo '`pre-commit` not found.' 1>&2
    fi
fi
